server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

application:
  choosing-cleaner-price: 20000
  default-rating: 4
  mail:
    mail: "bin.luoi.pc@gmail.com"
    password: "bnbo mxwr mnmc cifx"
  security:
    jwt:
      secret-key: e893d203a96a80a688c1c61d6fab849bb999516b6d3af3f7d4f0c188ffae21bc
      expiration: 30 # minutes
